#!/bin/bash

function nc_client_test {
  if nc -z $1 $2 &> /dev/null; then
    echo -e "$1:$2\tSucceeded"
  else
    echo -e "$1:$2\tfailed"
  fi
}

function test_client_network {
  NETWORK_TEST_HOSTS="$1"

  NETWORK_TESTING_PORTS="$2"

  for h in $NETWORK_TEST_HOSTS; do
    for i in $NETWORK_TESTING_PORTS; do
      nc_client_test $h $i
    done
  done

}

function ping_test {
  PING_WAIT=2
  PING_COUNT=1
  if `ping -W ${PING_WAIT} -c ${PING_COUNT} $1 > /dev/null 2> /dev/null`; then
    echo "$1 ping succeeded"
  else
    echo "$1 ping failed"
  fi
}

function test_client_ping {
  NETWORK_TEST_HOSTS="$1"

  for h in $NETWORK_TEST_HOSTS; do
    ping_test $h
  done

}

test_client_network "$1" "$2"